
import { Language } from './types';

export const translations: Record<Language, Record<string, string>> = {
    en: {
        welcome: 'Welcome to Cultur',
        chooseLanguage: 'Choose your language',
        english: 'English',
        russian: 'Russian',
        login: 'Login',
        register: 'Register',
        nickname: 'Nickname',
        email: 'Email',
        password: 'Password',
        authPrompt: 'Please log in or register to continue.',
        dashboard: 'Dashboard',
        newsFeed: 'Feed',
        adminPanel: 'Admin Panel',
        userManagement: 'User Management',
        contentManagement: 'Content Management',
        logout: 'Logout',
        all: 'All',
        news: 'News',
        videos: 'Videos',
        mixes: 'Mixes',
        releases: 'Releases',
        myPlaylists: 'My Playlists',
        publicPlaylists: 'Public Playlists',
        createPlaylist: 'Create Playlist',
        playlistName: 'Playlist Name',
        addToPlaylist: 'Add to Playlist',
        offlineNote: 'Playlists are saved on this device for offline access.',
        generateWithAI: 'Generate with AI',
        title: 'Title',
        description: 'Description',
        imageURL: 'Image URL',
        contentURL: 'Content URL',
        type: 'Type',
        publish: 'Publish',
        edit: 'Edit',
        delete: 'Delete',
        role: 'Role',
        actions: 'Actions',
        save: 'Save',
        cancel: 'Cancel',
        confirmDelete: 'Are you sure you want to delete this?',
        promoteToModerator: 'Promote to Moderator',
        demoteToUser: 'Demote to User',
        createUser: 'Create User',
        profile: 'Profile',
        updateProfile: 'Update Profile',
        newPassword: 'New Password (leave blank to keep current)',
        profileUpdated: 'Profile updated successfully!',
        makePublic: 'Make Public',
        by: 'by',
        title_en: 'Title (EN)',
        title_ru: 'Title (RU)',
        description_en: 'Description (EN)',
        description_ru: 'Description (RU)',
        uploadAudio: 'Upload Audio File',
        contentFile: 'Content File',
        like: 'Like',
        comment: 'Comment',
        comments: 'Comments',
        addComment: 'Add a comment...',
        postComment: 'Post',
        noComments: 'No comments yet.',
        viewComments: 'View Comments',
        liveStream: 'Live Stream',
        streamStartsIn: 'Stream starts in:',
        streamIsLive: 'Stream is Live!',
        updateStream: 'Update Stream',
        streamTitle: 'Stream Title',
        startTime: 'Start Time',
        embedCode: 'Embed HTML Code',
        liveChat: 'Live Chat',
        sendMessage: 'Send a message...',
        send: 'Send',
    },
    ru: {
        welcome: 'Добро пожаловать в Cultur',
        chooseLanguage: 'Выберите ваш язык',
        english: 'Английский',
        russian: 'Русский',
        login: 'Вход',
        register: 'Регистрация',
        nickname: 'Никнейм',
        email: 'Почта',
        password: 'Пароль',
        authPrompt: 'Пожалуйста, войдите или зарегистрируйтесь, чтобы продолжить.',
        dashboard: 'Панель управления',
        newsFeed: 'Лента',
        adminPanel: 'Админ-панель',
        userManagement: 'Управление пользователями',
        contentManagement: 'Управление контентом',
        logout: 'Выйти',
        all: 'Все',
        news: 'Новости',
        videos: 'Видео',
        mixes: 'Миксы',
        releases: 'Релизы',
        myPlaylists: 'Мои плейлисты',
        publicPlaylists: 'Публичные плейлисты',
        createPlaylist: 'Создать плейлист',
        playlistName: 'Название плейлиста',
        addToPlaylist: 'Добавить в плейлист',
        offlineNote: 'Плейлисты сохраняются на этом устройстве для оффлайн доступа.',
        generateWithAI: 'Сгенерировать с ИИ',
        title: 'Заголовок',
        description: 'Описание',
        imageURL: 'URL изображения',
        contentURL: 'URL контента',
        type: 'Тип',
        publish: 'Опубликовать',
        edit: 'Редактировать',
        delete: 'Удалить',
        role: 'Роль',
        actions: 'Действия',
        save: 'Сохранить',
        cancel: 'Отмена',
        confirmDelete: 'Вы уверены, что хотите удалить это?',
        promoteToModerator: 'Назначить модератором',
        demoteToUser: 'Разжаловать до пользователя',
        createUser: 'Создать пользователя',
        profile: 'Профиль',
        updateProfile: 'Обновить профиль',
        newPassword: 'Новый пароль (оставьте пустым, чтобы не менять)',
        profileUpdated: 'Профиль успешно обновлен!',
        makePublic: 'Сделать публичным',
        by: 'от',
        title_en: 'Заголовок (EN)',
        title_ru: 'Заголовок (RU)',
        description_en: 'Описание (EN)',
        description_ru: 'Описание (RU)',
        uploadAudio: 'Загрузить аудиофайл',
        contentFile: 'Файл контента',
        like: 'Нравится',
        comment: 'Комментарий',
        comments: 'Комментарии',
        addComment: 'Добавьте комментарий...',
        postComment: 'Опубликовать',
        noComments: 'Комментариев пока нет.',
        viewComments: 'Смотреть комментарии',
        liveStream: 'Прямой эфир',
        streamStartsIn: 'Эфир начнется через:',
        streamIsLive: 'Эфир уже идет!',
        updateStream: 'Обновить стрим',
        streamTitle: 'Название стрима',
        startTime: 'Время начала',
        embedCode: 'HTML-код для вставки',
        liveChat: 'Чат трансляции',
        sendMessage: 'Отправить сообщение...',
        send: 'Отправить',
    }
};